import { defineType, defineField } from "sanity";

export default defineType({
  name: "contactPage",
  title: "Contact Page",
  type: "document",
  fields: [
    defineField({
      name: "heroKicker",
      title: "Hero Kicker",
      type: "string",
      initialValue: "Get in Touch",
    }),
    defineField({
      name: "heroTitle",
      title: "Hero Title",
      type: "text",
      initialValue: "Let's Create Meaningful\nArtistic Connections",
    }),
    defineField({
      name: "heroTitleItalic",
      title: "Hero Title Italic Word/Phrase",
      type: "string",
      initialValue: "Artistic Connections",
    }),
    defineField({
      name: "heroBody",
      title: "Hero Body",
      type: "text",
      initialValue: "Whether you're an art collector, artist, curator, or enthusiast, we'd love to hear from you.",
    }),
    defineField({
      name: "formKicker",
      title: "Form Section Kicker",
      type: "string",
      initialValue: "Send Us a Message",
    }),
    defineField({
      name: "formTitle",
      title: "Form Section Title",
      type: "text",
      initialValue: "We'd love to hear\nfrom you",
    }),
    defineField({
      name: "formTitleItalic",
      title: "Form Title Italic Word",
      type: "string",
      initialValue: "from you",
    }),
    defineField({
      name: "personalInfoLabel",
      title: "Personal Info Section Label",
      type: "string",
      initialValue: "Personal Information",
    }),
    defineField({
      name: "nameFieldLabel",
      title: "Name Field Label",
      type: "string",
      initialValue: "Full Name",
    }),
    defineField({
      name: "emailFieldLabel",
      title: "Email Field Label",
      type: "string",
      initialValue: "Email Address",
    }),
    defineField({
      name: "phoneFieldLabel",
      title: "Phone Field Label",
      type: "string",
      initialValue: "Phone Number (Optional)",
    }),
    defineField({
      name: "inquiryDetailsLabel",
      title: "Inquiry Details Label",
      type: "string",
      initialValue: "Inquiry Details",
    }),
    defineField({
      name: "inquiryTypeLabel",
      title: "Inquiry Type Label",
      type: "string",
      initialValue: "Inquiry Type",
    }),
    defineField({
      name: "subjectLabel",
      title: "Subject Label",
      type: "string",
      initialValue: "Subject",
    }),
    defineField({
      name: "messageLabel",
      title: "Message Label",
      type: "string",
      initialValue: "Message",
    }),
    defineField({
      name: "uploadLabel",
      title: "Upload Label",
      type: "string",
      initialValue: "Upload Artwork / Reference Image / Document (Optional)",
    }),
    defineField({
      name: "uploadButtonText",
      title: "Upload Button Text",
      type: "string",
      initialValue: "Choose File",
    }),
    defineField({
      name: "submitButtonText",
      title: "Submit Button Text",
      type: "string",
      initialValue: "Send Inquiry",
    }),
    defineField({
      name: "inquiryTypes",
      title: "Inquiry Type Options",
      type: "array",
      of: [{ type: "string" }],
      initialValue: [
        "Artwork Purchase",
        "Artist Collaboration",
        "Exhibition Inquiry",
        "Private Event Booking",
        "Gallery Visit",
        "Partnership Opportunity",
        "General Inquiry",
      ],
    }),
    defineField({
      name: "visitKicker",
      title: "Visit Section Kicker",
      type: "string",
      initialValue: "Visit Us",
    }),
    defineField({
      name: "addressLabel",
      title: "Address Label",
      type: "string",
      initialValue: "Address",
    }),
    defineField({
      name: "hoursLabel",
      title: "Hours Label",
      type: "string",
      initialValue: "Opening Hours",
    }),
    defineField({
      name: "phoneLabel",
      title: "Phone Label",
      type: "string",
      initialValue: "Phone",
    }),
    defineField({
      name: "emailLabel",
      title: "Email Label",
      type: "string",
      initialValue: "Email",
    }),
    defineField({
      name: "whyConnectKicker",
      title: "Why Connect Kicker",
      type: "string",
      initialValue: "Why Connect With Sahaj?",
    }),
    defineField({
      name: "features",
      title: "Why Connect Features",
      type: "array",
      of: [{
        type: "object",
        fields: [
          { name: "title", title: "Title", type: "string" },
          { name: "desc", title: "Description", type: "text" },
          { name: "icon", title: "Icon Character", type: "string" },
        ],
        preview: { select: { title: "title" } },
      }],
      initialValue: [
        { title: "Curated Art Experiences", desc: "Each interaction is shaped around your vision — whether acquiring a piece or commissioning something entirely new.", icon: "✦" },
        { title: "Emerging & Established Artists", desc: "We represent voices from across the creative spectrum — from rising talents to masters with decades of practice.", icon: "✦" },
        { title: "Private Exhibitions & Events", desc: "Intimate viewings, curated walkthroughs, and exclusive previews tailored for collectors and connoisseurs.", icon: "✦" },
      ],
    }),
    defineField({
      name: "mapUrl",
      title: "Google Maps URL",
      type: "url",
      initialValue: "https://www.google.com/maps?um=1&ie=UTF-8&fb=1&gl=in&sa=X&geocode=KWNN2o4_m145MTOJ5URhNfzK&daddr=Shop+-+02,+Palak+Prime,+Ambli+Rd,+opp.+DoubleTree+by+Hilton+Hotel,+nr.+Antriksh+colony+BRTS+Bus+Stand,+Ambli,+Ahmedabad,+Gujarat+380058",
    }),
    defineField({
      name: "mapLabel",
      title: "Map Click Label",
      type: "string",
      initialValue: "Click to open in Google Maps",
    }),
    defineField({
      name: "footerText",
      title: "Footer Text",
      type: "string",
      initialValue: "Designed to inspire creativity",
    }),
  ],
});
