import { defineType, defineField } from "sanity";

export default defineType({
  name: "sahajPage",
  title: "SAHAJ Page",
  type: "document",
  fields: [
    defineField({
      name: "heroTitle",
      title: "Hero Title",
      type: "string",
      initialValue: "SAHAJ Gallery is the artistic extension of NDH House",
    }),
    defineField({
      name: "heroBody",
      title: "Hero Body Paragraphs",
      type: "array",
      of: [{ type: "text" }],
      initialValue: [
        "Founded on the belief that meaningful spaces are enriched by stories, culture, and art. Emerging from an architectural practice, SAHAJ serves as a gallery and creative destination where architecture meets art and craftsmanship — showcasing thoughtfully curated artworks that complement and elevate contemporary interiors.",
        "At SAHAJ, every piece is conceived with a designer's perspective, bridging art, materiality, and spatial experience. Through handcrafted creations, wall art, decorative installations, and bespoke artistic expressions, SAHAJ transforms walls into narratives and spaces into experiences.",
      ],
    }),
    defineField({
      name: "heroGetInTouchText",
      title: "Hero Get In Touch Button Text",
      type: "string",
      initialValue: "Get in Touch",
    }),
    defineField({
      name: "partnershipKicker",
      title: "Partnership Section Kicker",
      type: "string",
      initialValue: "The Collaboration",
    }),
    defineField({
      name: "partnershipSubtitle",
      title: "Partnership Subtitle",
      type: "string",
      initialValue: "STUDIO SHIKSHPATRI × KARIGARI STUDIO",
    }),
    defineField({
      name: "partnershipBody",
      title: "Partnership Body",
      type: "array",
      of: [{ type: "text" }],
      initialValue: [
        "SAHAJ Gallery collaborates with artists, designers, and creative studios to bring distinctive art forms into architectural spaces.",
        "",
        "Studio Shikashapatrika – Calligraphy Series\nA collection that celebrates the beauty of script, language, and expression through contemporary calligraphic artworks, blending tradition with modern aesthetics.",
        "",
        "Karigari Studio – Mosaic Series\nAn exploration of craftsmanship and materiality through handcrafted mosaic artworks, creating intricate compositions that add texture, depth, and character to interiors.",
        "",
        "Through these collaborations, SAHAJ Gallery seeks to curate and explore innovative artistic mediums and materials, combining the expertise of skilled artists with thoughtful design sensibilities.",
      ],
    }),
    defineField({
      name: "studioLogo",
      title: "Studio Shikshaptri Logo",
      type: "image",
    }),
    defineField({
      name: "studioLabel",
      title: "Studio Label",
      type: "string",
      initialValue: "STUDIO SHIKSHPATRI",
    }),
    defineField({
      name: "karigariLogo",
      title: "Karigari Studio Logo",
      type: "image",
    }),
    defineField({
      name: "karigariLabel",
      title: "Karigari Label",
      type: "string",
      initialValue: "KARIGARI STUDIO",
    }),
    defineField({
      name: "partnershipFooterLabel",
      title: "Partnership Footer Label",
      type: "string",
      initialValue: "Collobration with sahaj",
    }),
    defineField({
      name: "fenilVideo",
      title: "Fenil Testimonial Video",
      type: "file",
      options: { accept: "video/mp4" },
    }),
    defineField({
      name: "fenilQuote",
      title: "Fenil Quote",
      type: "text",
      initialValue: "\"Some voices carry authority not because of how loudly they speak, but because of everything they have come to understand.\"",
    }),
    defineField({
      name: "fenilBody",
      title: "Fenil Body Paragraphs",
      type: "array",
      of: [{ type: "text" }],
      initialValue: [
        "CA. CS. Dr. Fenil Shah (@fenil_spark), a name that spans across domains, from finance to law, from governance to mentorship, brings with him a rare clarity of thought.",
        "His reflections on SAHAJ feel less like praise and more like recognition, a perspective that sees both value and vision. Not just seeing art, but understanding what it stands for.",
      ],
    }),
    defineField({
      name: "fenilInstagramHandle",
      title: "Fenil Instagram Handle",
      type: "string",
      initialValue: "@fenil_spark",
    }),
    defineField({
      name: "fenilInstagramUrl",
      title: "Fenil Instagram URL",
      type: "url",
      initialValue: "https://www.instagram.com/fenil_spark/",
    }),
    defineField({
      name: "fenilDisplayName",
      title: "Fenil Display Name",
      type: "string",
      initialValue: "CA. CS. Dr. Fenil Shah",
    }),
    defineField({
      name: "dhrutiVideo",
      title: "Dhruti Testimonial Video",
      type: "file",
      options: { accept: "video/mp4" },
    }),
    defineField({
      name: "dhrutiQuote",
      title: "Dhruti Quote",
      type: "text",
      initialValue: "\"An artist's opinion on another artist's work is always a confession.\"",
    }),
    defineField({
      name: "dhrutiBody",
      title: "Dhruti Body Paragraphs",
      type: "array",
      of: [{ type: "text" }],
      initialValue: [
        "Dhruti Panchal (@dhruti_artfromheart) is one such voice in Ahmedabad's art landscape. Her appreciation of SAHAJ is meaningful not simply because it is praise, but because it is recognition — one artist recognizing the sincerity, effort, and intention behind the work of fellow makers.",
        "For us, SAHAJ has always been more than a gallery. It is an evolving dialogue between art, craftsmanship, architecture, and the people who engage with them. It is a space where materials become stories, where hands shape ideas into tangible expressions, and where creativity finds a place to belong.",
        "Moments like these reaffirm our purpose. They remind us that meaningful work is seen, understood, and valued by those who share the same commitment to creating with authenticity and heart.",
      ],
    }),
    defineField({
      name: "dhrutiInstagramHandle",
      title: "Dhruti Instagram Handle",
      type: "string",
      initialValue: "@dhruti_artfromheart",
    }),
    defineField({
      name: "dhrutiInstagramUrl",
      title: "Dhruti Instagram URL",
      type: "url",
      initialValue: "https://www.instagram.com/dhruti_artfromheart/",
    }),
    defineField({
      name: "dhrutiDisplayName",
      title: "Dhruti Display Name",
      type: "string",
      initialValue: "Dhruti Panchal",
    }),
    defineField({
      name: "handsVideo",
      title: "Hands of SAHAJ Video",
      type: "file",
      options: { accept: "video/mp4" },
    }),
    defineField({
      name: "handsTitle",
      title: "Hands of SAHAJ Title",
      type: "string",
      initialValue: "Hands of SAHAJ",
    }),
    defineField({
      name: "handsBody",
      title: "Hands of SAHAJ Body",
      type: "array",
      of: [{ type: "text" }],
      initialValue: [
        "An imprint of passion, crafted by the artists of SAHAJ.",
        "Every creation carries the touch of its maker — a reflection of skill, dedication, and artistic spirit. More than an object, each piece tells a story, shaped not only by hands but also by imagination, emotion, and heart.",
        "At SAHAJ, we celebrate the human connection behind every artwork, where craftsmanship transforms materials into meaningful expressions. Through the hands of our artists, ideas become creations that enrich spaces, evoke emotions, and inspire lasting connections.",
      ],
    }),
    defineField({
      name: "handsArtists",
      title: "Hands Artists List",
      type: "array",
      of: [{ type: "string" }],
      initialValue: ["Nehal Rathod", "Chintu Bhalani", "Hetakshi Chauhan", "Hansni Sharma", "Arya Jadav", "Pooja Bhavsar"],
    }),
    defineField({
      name: "whatWeDoKicker",
      title: "What We Do Kicker",
      type: "string",
      initialValue: "What We Do",
    }),
    defineField({
      name: "whatWeDoTitle",
      title: "What We Do Title",
      type: "string",
      initialValue: "Our Offering",
    }),
    defineField({
      name: "services",
      title: "Services / Offerings",
      type: "array",
      of: [{
        type: "object",
        fields: [
          { name: "number", title: "Number", type: "string" },
          { name: "title", title: "Title", type: "string" },
          { name: "body", title: "Body", type: "text" },
        ],
        preview: { select: { title: "title", subtitle: "number" } },
      }],
      initialValue: [
        { number: "01", title: "Commissioned Works", body: "Original pieces conceived in dialogue with you — shaped by space, intention, and the quiet language of your everyday rituals." },
        { number: "02", title: "Architectural Integration", body: "We work alongside your architect to weave art into walls, light, and proportion — so that nothing feels placed, only inevitable." },
        { number: "03", title: "White Glove Installation", body: "From our studio to your space.\nPerfectly placed.\nWhite-glove handling.\nPrecision installation.\nSeamless integration.\nBecause art deserves respect." },
      ],
    }),
    defineField({
      name: "spaceAddressKicker",
      title: "Space Address Kicker",
      type: "string",
      initialValue: "Address",
    }),
    defineField({
      name: "spaceHoursKicker",
      title: "Space Hours Kicker",
      type: "string",
      initialValue: "Hours",
    }),
    defineField({
      name: "spaceContactKicker",
      title: "Space Contact Kicker",
      type: "string",
      initialValue: "Contact",
    }),
    defineField({
      name: "spaceImage",
      title: "Space Image",
      type: "image",
    }),
    defineField({
      name: "spaceMapUrl",
      title: "Space Google Maps URL",
      type: "url",
      initialValue: "https://www.google.com/maps?um=1&ie=UTF-8&fb=1&gl=in&sa=X&geocode=KWNN2o4_m145MTOJ5URhNfzK&daddr=Shop+-+02,+Palak+Prime,+Ambli+Rd,+opp.+DoubleTree+by+Hilton+Hotel,+nr.+Antriksh+colony+BRTS+Bus+Stand,+Ambli,+Ahmedabad,+Gujarat+380058",
    }),
    defineField({
      name: "spaceDirectionsText",
      title: "Directions Button Text",
      type: "string",
      initialValue: "Get Directions",
    }),
    defineField({
      name: "instagramUrl",
      title: "Instagram URL",
      type: "url",
      initialValue: "https://www.instagram.com/sahajgallery/",
    }),
    defineField({
      name: "instagramLabel",
      title: "Instagram Label",
      type: "string",
      initialValue: "Instagram",
    }),
    defineField({
      name: "ctaKicker",
      title: "CTA Kicker",
      type: "string",
      initialValue: "Let's Begin",
    }),
    defineField({
      name: "ctaTitle",
      title: "CTA Title",
      type: "text",
      initialValue: "We'd love to hear\nfrom you",
    }),
    defineField({
      name: "ctaTitleItalic",
      title: "CTA Title Italic Word",
      type: "string",
      initialValue: "from you",
    }),
    defineField({
      name: "ctaBody",
      title: "CTA Body",
      type: "text",
      initialValue: "Whether you're looking to commission a piece, integrate art into your space, or simply explore — reach out. We'd be honoured to guide you.",
    }),
    defineField({
      name: "ctaButtonText",
      title: "CTA Button Text",
      type: "string",
      initialValue: "Contact Us",
    }),
    defineField({
      name: "ctaSecondaryButtonText",
      title: "CTA Secondary Button Text",
      type: "string",
      initialValue: "View Gallery",
    }),
    defineField({
      name: "footerText",
      title: "Footer Text",
      type: "string",
      initialValue: "A NDH House Partnership · Ahmedabad, Gujarat",
    }),
    defineField({
      name: "footerDirectionsText",
      title: "Footer Directions Text",
      type: "string",
      initialValue: "Directions",
    }),
    defineField({
      name: "footerCallText",
      title: "Footer Call Text",
      type: "string",
      initialValue: "Call",
    }),
  ],
});
